/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_creator_v202501

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance{}

// AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance struct for AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance
type AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance struct {
    // The total number of products sold in history
    HistoricalSoldQuantity *int32 `json:"historical_sold_quantity,omitempty"`
}

// NewAffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance instantiates a new AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance() *AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance {
    this := AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance{}
    return &this
}

// NewAffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformanceWithDefaults instantiates a new AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformanceWithDefaults() *AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance {
    this := AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance{}
    return &this
}

// GetHistoricalSoldQuantity returns the HistoricalSoldQuantity field value if set, zero value otherwise.
func (o *AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance) GetHistoricalSoldQuantity() int32 {
    if o == nil || utils.IsNil(o.HistoricalSoldQuantity) {
        var ret int32
        return ret
    }
    return *o.HistoricalSoldQuantity
}

// GetHistoricalSoldQuantityOk returns a tuple with the HistoricalSoldQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance) GetHistoricalSoldQuantityOk() (*int32, bool) {
    if o == nil || utils.IsNil(o.HistoricalSoldQuantity) {
        return nil, false
    }
    return o.HistoricalSoldQuantity, true
}

// HasHistoricalSoldQuantity returns a boolean if a field has been set.
func (o *AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance) HasHistoricalSoldQuantity() bool {
    if o != nil && !utils.IsNil(o.HistoricalSoldQuantity) {
        return true
    }

    return false
}

// SetHistoricalSoldQuantity gets a reference to the given int32 and assigns it to the HistoricalSoldQuantity field.
func (o *AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance) SetHistoricalSoldQuantity(v int32) {
    o.HistoricalSoldQuantity = &v
}

func (o AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.HistoricalSoldQuantity) {
        toSerialize["historical_sold_quantity"] = o.HistoricalSoldQuantity
    }
    return toSerialize, nil
}

type NullableAffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance struct {
	value *AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance
	isSet bool
}

func (v NullableAffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance) Get() *AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance {
	return v.value
}

func (v *NullableAffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance) Set(val *AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance(val *AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance) *NullableAffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance {
	return &NullableAffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance{value: val, isSet: true}
}

func (v NullableAffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsMarketPerformance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


