/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_seller_v202405

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop{}

// AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop struct for AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop
type AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop struct {
    // The name of the TikTok shop.
    Name *string `json:"name,omitempty"`
}

// NewAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop instantiates a new AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop() *AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop {
    this := AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop{}
    return &this
}

// NewAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShopWithDefaults instantiates a new AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShopWithDefaults() *AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop {
    this := AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop{}
    return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop) GetName() string {
    if o == nil || utils.IsNil(o.Name) {
        var ret string
        return ret
    }
    return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop) GetNameOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Name) {
        return nil, false
    }
    return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop) HasName() bool {
    if o != nil && !utils.IsNil(o.Name) {
        return true
    }

    return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop) SetName(v string) {
    o.Name = &v
}

func (o AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Name) {
        toSerialize["name"] = o.Name
    }
    return toSerialize, nil
}

type NullableAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop struct {
	value *AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop
	isSet bool
}

func (v NullableAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop) Get() *AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop {
	return v.value
}

func (v *NullableAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop) Set(val *AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop(val *AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop) *NullableAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop {
	return &NullableAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop{value: val, isSet: true}
}

func (v NullableAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsShop) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


