/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_v202309

import (
    "encoding/json"
    "github.com/Yuttachai-101/api_tiktok/utils"
)

            // checks if the Affiliate202309GetShopProductsResponseDataProductsPrice type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Affiliate202309GetShopProductsResponseDataProductsPrice{}

// Affiliate202309GetShopProductsResponseDataProductsPrice struct for Affiliate202309GetShopProductsResponseDataProductsPrice
type Affiliate202309GetShopProductsResponseDataProductsPrice struct {
    // Product price with two decimal places.
    Amount *string `json:"amount,omitempty"`
    // Product price currency, based on region where creators can sell.
    Currency *string `json:"currency,omitempty"`
}

// NewAffiliate202309GetShopProductsResponseDataProductsPrice instantiates a new Affiliate202309GetShopProductsResponseDataProductsPrice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliate202309GetShopProductsResponseDataProductsPrice() *Affiliate202309GetShopProductsResponseDataProductsPrice {
    this := Affiliate202309GetShopProductsResponseDataProductsPrice{}
    return &this
}

// NewAffiliate202309GetShopProductsResponseDataProductsPriceWithDefaults instantiates a new Affiliate202309GetShopProductsResponseDataProductsPrice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliate202309GetShopProductsResponseDataProductsPriceWithDefaults() *Affiliate202309GetShopProductsResponseDataProductsPrice {
    this := Affiliate202309GetShopProductsResponseDataProductsPrice{}
    return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *Affiliate202309GetShopProductsResponseDataProductsPrice) GetAmount() string {
    if o == nil || utils.IsNil(o.Amount) {
        var ret string
        return ret
    }
    return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Affiliate202309GetShopProductsResponseDataProductsPrice) GetAmountOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Amount) {
        return nil, false
    }
    return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *Affiliate202309GetShopProductsResponseDataProductsPrice) HasAmount() bool {
    if o != nil && !utils.IsNil(o.Amount) {
        return true
    }

    return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *Affiliate202309GetShopProductsResponseDataProductsPrice) SetAmount(v string) {
    o.Amount = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *Affiliate202309GetShopProductsResponseDataProductsPrice) GetCurrency() string {
    if o == nil || utils.IsNil(o.Currency) {
        var ret string
        return ret
    }
    return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Affiliate202309GetShopProductsResponseDataProductsPrice) GetCurrencyOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Currency) {
        return nil, false
    }
    return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *Affiliate202309GetShopProductsResponseDataProductsPrice) HasCurrency() bool {
    if o != nil && !utils.IsNil(o.Currency) {
        return true
    }

    return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *Affiliate202309GetShopProductsResponseDataProductsPrice) SetCurrency(v string) {
    o.Currency = &v
}

func (o Affiliate202309GetShopProductsResponseDataProductsPrice) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Affiliate202309GetShopProductsResponseDataProductsPrice) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Amount) {
        toSerialize["amount"] = o.Amount
    }
    if !utils.IsNil(o.Currency) {
        toSerialize["currency"] = o.Currency
    }
    return toSerialize, nil
}

type NullableAffiliate202309GetShopProductsResponseDataProductsPrice struct {
	value *Affiliate202309GetShopProductsResponseDataProductsPrice
	isSet bool
}

func (v NullableAffiliate202309GetShopProductsResponseDataProductsPrice) Get() *Affiliate202309GetShopProductsResponseDataProductsPrice {
	return v.value
}

func (v *NullableAffiliate202309GetShopProductsResponseDataProductsPrice) Set(val *Affiliate202309GetShopProductsResponseDataProductsPrice) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliate202309GetShopProductsResponseDataProductsPrice) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliate202309GetShopProductsResponseDataProductsPrice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliate202309GetShopProductsResponseDataProductsPrice(val *Affiliate202309GetShopProductsResponseDataProductsPrice) *NullableAffiliate202309GetShopProductsResponseDataProductsPrice {
	return &NullableAffiliate202309GetShopProductsResponseDataProductsPrice{value: val, isSet: true}
}

func (v NullableAffiliate202309GetShopProductsResponseDataProductsPrice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliate202309GetShopProductsResponseDataProductsPrice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


