/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Affiliate202309GetShopProductsResponseDataProductsImages type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Affiliate202309GetShopProductsResponseDataProductsImages{}

// Affiliate202309GetShopProductsResponseDataProductsImages struct for Affiliate202309GetShopProductsResponseDataProductsImages
type Affiliate202309GetShopProductsResponseDataProductsImages struct {
    // The height of the product image.
    Height *int32 `json:"height,omitempty"`
    // The URL of the product image.
    Url *string `json:"url,omitempty"`
    // The width of the product image.
    Width *int32 `json:"width,omitempty"`
}

// NewAffiliate202309GetShopProductsResponseDataProductsImages instantiates a new Affiliate202309GetShopProductsResponseDataProductsImages object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliate202309GetShopProductsResponseDataProductsImages() *Affiliate202309GetShopProductsResponseDataProductsImages {
    this := Affiliate202309GetShopProductsResponseDataProductsImages{}
    return &this
}

// NewAffiliate202309GetShopProductsResponseDataProductsImagesWithDefaults instantiates a new Affiliate202309GetShopProductsResponseDataProductsImages object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliate202309GetShopProductsResponseDataProductsImagesWithDefaults() *Affiliate202309GetShopProductsResponseDataProductsImages {
    this := Affiliate202309GetShopProductsResponseDataProductsImages{}
    return &this
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *Affiliate202309GetShopProductsResponseDataProductsImages) GetHeight() int32 {
    if o == nil || utils.IsNil(o.Height) {
        var ret int32
        return ret
    }
    return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Affiliate202309GetShopProductsResponseDataProductsImages) GetHeightOk() (*int32, bool) {
    if o == nil || utils.IsNil(o.Height) {
        return nil, false
    }
    return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *Affiliate202309GetShopProductsResponseDataProductsImages) HasHeight() bool {
    if o != nil && !utils.IsNil(o.Height) {
        return true
    }

    return false
}

// SetHeight gets a reference to the given int32 and assigns it to the Height field.
func (o *Affiliate202309GetShopProductsResponseDataProductsImages) SetHeight(v int32) {
    o.Height = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *Affiliate202309GetShopProductsResponseDataProductsImages) GetUrl() string {
    if o == nil || utils.IsNil(o.Url) {
        var ret string
        return ret
    }
    return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Affiliate202309GetShopProductsResponseDataProductsImages) GetUrlOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Url) {
        return nil, false
    }
    return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *Affiliate202309GetShopProductsResponseDataProductsImages) HasUrl() bool {
    if o != nil && !utils.IsNil(o.Url) {
        return true
    }

    return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *Affiliate202309GetShopProductsResponseDataProductsImages) SetUrl(v string) {
    o.Url = &v
}

// GetWidth returns the Width field value if set, zero value otherwise.
func (o *Affiliate202309GetShopProductsResponseDataProductsImages) GetWidth() int32 {
    if o == nil || utils.IsNil(o.Width) {
        var ret int32
        return ret
    }
    return *o.Width
}

// GetWidthOk returns a tuple with the Width field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Affiliate202309GetShopProductsResponseDataProductsImages) GetWidthOk() (*int32, bool) {
    if o == nil || utils.IsNil(o.Width) {
        return nil, false
    }
    return o.Width, true
}

// HasWidth returns a boolean if a field has been set.
func (o *Affiliate202309GetShopProductsResponseDataProductsImages) HasWidth() bool {
    if o != nil && !utils.IsNil(o.Width) {
        return true
    }

    return false
}

// SetWidth gets a reference to the given int32 and assigns it to the Width field.
func (o *Affiliate202309GetShopProductsResponseDataProductsImages) SetWidth(v int32) {
    o.Width = &v
}

func (o Affiliate202309GetShopProductsResponseDataProductsImages) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Affiliate202309GetShopProductsResponseDataProductsImages) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Height) {
        toSerialize["height"] = o.Height
    }
    if !utils.IsNil(o.Url) {
        toSerialize["url"] = o.Url
    }
    if !utils.IsNil(o.Width) {
        toSerialize["width"] = o.Width
    }
    return toSerialize, nil
}

type NullableAffiliate202309GetShopProductsResponseDataProductsImages struct {
	value *Affiliate202309GetShopProductsResponseDataProductsImages
	isSet bool
}

func (v NullableAffiliate202309GetShopProductsResponseDataProductsImages) Get() *Affiliate202309GetShopProductsResponseDataProductsImages {
	return v.value
}

func (v *NullableAffiliate202309GetShopProductsResponseDataProductsImages) Set(val *Affiliate202309GetShopProductsResponseDataProductsImages) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliate202309GetShopProductsResponseDataProductsImages) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliate202309GetShopProductsResponseDataProductsImages) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliate202309GetShopProductsResponseDataProductsImages(val *Affiliate202309GetShopProductsResponseDataProductsImages) *NullableAffiliate202309GetShopProductsResponseDataProductsImages {
	return &NullableAffiliate202309GetShopProductsResponseDataProductsImages{value: val, isSet: true}
}

func (v NullableAffiliate202309GetShopProductsResponseDataProductsImages) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliate202309GetShopProductsResponseDataProductsImages) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


