/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_seller_v202406

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar{}

// AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar struct for AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar
type AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar struct {
    // The URL for the creator's TikTok profile avatar.
    Url *string `json:"url,omitempty"`
}

// NewAffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar instantiates a new AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar() *AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar {
    this := AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar{}
    return &this
}

// NewAffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatarWithDefaults instantiates a new AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatarWithDefaults() *AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar {
    this := AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar{}
    return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar) GetUrl() string {
    if o == nil || utils.IsNil(o.Url) {
        var ret string
        return ret
    }
    return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar) GetUrlOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Url) {
        return nil, false
    }
    return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar) HasUrl() bool {
    if o != nil && !utils.IsNil(o.Url) {
        return true
    }

    return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar) SetUrl(v string) {
    o.Url = &v
}

func (o AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Url) {
        toSerialize["url"] = o.Url
    }
    return toSerialize, nil
}

type NullableAffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar struct {
	value *AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar
	isSet bool
}

func (v NullableAffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar) Get() *AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar {
	return v.value
}

func (v *NullableAffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar) Set(val *AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar(val *AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar) *NullableAffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar {
	return &NullableAffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar{value: val, isSet: true}
}

func (v NullableAffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


